# SPDX-FileCopyrightText: 2026 The jma-openapi contributors
#
# SPDX-License-Identifier: MPL-2.0

[tools]
go = "1.26.1"
uv = "latest"

[tasks.license-annotate]
run = "./scripts/reuse-annotate.sh"

[tasks.license-lint]
run = "uvx reuse lint"
